#--------------------------------------------------------------------------------------
# This GitHub Actions workflow tests xen-bugtool in a Dom0-based self-hosted runner.
# Runs the checks when an authorized user comments the PR with: /run checks in dom0
#
# Pre-condition: A self-hosted github-runner, installed on a XenServer Dom0 needs to
# be registered for this repository and running. Instructions are found here:
# https://github.com/xenserver-next/status-report/settings/actions/runners/new
# Required additional software in Dom0: git and maybe other tools
# The github-runner needs to be installed as a regular user (create one with useradd)
# and run: echo "$NEW_USERNAME ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
# xen-bugtool needs to run as root, so at least it need to be runnable using sudo.
#--------------------------------------------------------------------------------------
# Based on:
# https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2
# https://github.com/zirkelc/github-actions-workflows/blob/main/.github/workflows/deploy-on-comment.yml
# Full course on GitHub Actions: https://youtu.be/TLB5MY9BBa4
#--------------------------------------------------------------------------------------

name: Run checks on xen-bugtool in Dom0
run-name: 'Test xen-bugtool for ${{ github.event_name }} by ${{ github.actor }}'

# Run on pushes and pull requests and allow to be triggered by comments
# Docs:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
on:
  pull_request:
    paths:
      - .github/workflows/dom0-tests.yml
      - xen-bugtool
  issue_comment:
    types: [created, edited]

# Docs: https://github.com/marketplace/actions/commit-status-updater#workflow-permissions
# and more info on https://github.com/actions/first-interaction/issues/10
# self-hosted runners need explicit write permission for:
permissions:
  pull-requests: write  # creating a comment
  statuses: write  #  # updating commit status

jobs:
  nested_template:
    uses: ./.github/workflows/run-all-entries-in-Dom0.yml
    # Restricted to Bernhard and Ross because this step runs the branch on a self-hosted runner:
    # They can trigger this workflow but creating or editing a PR comment with '/runtest entries'
    # Doc on contexts: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Only run this if this job is triggered on a pull request, and require
    # that this this triggered by a issue_comment, otherwise it the source must
    # not be another repository:
    if: ${{
      github.event.pull_request.head.repo.full_name == github.repository ||
      contains(fromJson('["bernhardkaindl", "rosslagerwall"]'), github.actor) ||
      (github.event.issue.pull_request && contains(github.event.comment.body, '/runtest dom0'))
      }}
